### ISSUE TITLE
Incomplete crawls dues to race-condition on crawl()

### ISSUE THREAD

**Issue by HugoMFernandes** [cgiffard/node-simplecrawler#298] opened 2016-07-12 16:01 UTC
If the combination of number of items and fetch time per item is high enough (when compared to the crawler's crawl interval), the crawler can stop crawling before processing the discovery phase.

A simple example of this problem would be:
- Set a low enough crawl interval (say, 1ms)
- Give the initial url to the crawler
- Watch the crawler stop crawling (normally) even though there are still items to be discovered

What is happening behind the scenes:

The crawler (i.e. lib/crawler.js) maintains an array and a counter (`_openRequests` and `_openListeners`, respectively) to know when it is safe to stop crawling (note: `_openRequests` was previously a counter as well).

Since the `fetchcomplete` event is triggered (and the array/counter updated) before reaching the discovery phase, the crawler can reach the next `crawl` step (i.e. the next `setInterval` tick) before having new items added to the queue (since the discovery phase is yet to run, even though the flags have already been updated). When this happens, the crawler (unexpectedly) stops normally.

**Comment by HugoMFernandes** [comment] 2016-07-12 16:53
Submitted a PR with a fix in line with the current behavior for `_openRequests` and `_openListeners`. Let me know if there are any problems.

**Comment by cgiffard** [comment] 2016-07-13 09:21
@HugoMFernandes Hrm, this is certainly unexpected — since simplecrawler's own discovery process is synchronous and triggered synchronously after emitting `fetchcomplete`, and, unless I'm misunderstanding something relatively fundamental (which, admittedly, is not impossible!) it should not be susceptible to race conditions. Are you using your own asynchronous discovery process?

In order to support asynchronous discovery or holding the crawler open while client code checked in with an async service, a hook (`crawler.wait()`) was added, which as you have observed, is what `_openListeners` corresponds to. Unless there's a bug with this code, I think it should support your use case: https://github.com/cgiffard/node-simplecrawler#waiting-for-asynchronous-event-listeners

If this code isn't working, or doesn't satisfy your case, I'd like to explore fixing it rather than adding a parallel mechanism for tracking.

I really appreciate the effort you've gone to to clearly list the steps for reproduction, but just so I can be absolutely certain we're on the same page with this, do you have a code sample which reliably reproduces the problem?

**Comment by cgiffard** [comment] 2016-07-13 09:22
Thanks for filing an issue, btw! :)

**Comment by HugoMFernandes** [comment] 2016-07-13 14:32
Hey @cgiffard ,

No problem. Basically, the code is not synchronous if the crawler needs to deflate/unzip the response content (in order to discover new items).

Here's a simple scenario reproducing the problem: https://github.com/HugoMFernandes/node-simplecrawler-i298

**Comment by cgiffard** [comment] 2016-07-15 00:53
Wanted to thank you sincerely for filing such a comprehensive test case — first time I've seen one that complete! Apologies for the delay in my response — I'll get a chance to look at this on the weekend I think.

**Comment by HugoMFernandes** [comment] 2016-07-15 08:50
No problem, cheers :)

**Closed** 2016-07-17 19:19 UTC

**Comment by fredrikekelund** [comment] 2016-07-17 19:24
@HugoMFernandes thanks a lot for reporting this! :pray: The issue seemed to be that the queue item would be marked as fetched before the unzipping was done, so rather than maintaining an `_openDiscoveries` counter, I opted for a solution where the queue item is marked as fetched only after it's been unzipped.

I used your test case to debug the issue and could confirm that my changes indeed fixed the problem there!

I'll be sure to thank you in the 1.0.0 release notes as well :)

**Comment by HugoMFernandes** [comment] 2016-07-18 10:10
@fredrikekelund That's fine. I only added the `_openDiscoveries` counter because I assumed you wanted to keep fetching and discovering as different concepts (I hadn't even looked at master at this point / just 0.7). I prefer it this way as well.

Thanks for looking into this :)

**Comment by cgiffard** [comment] 2016-07-18 10:26
@HugoMFernandes Thanks again for going to the trouble of submitting such a comprehensive test case!
