### ISSUE TITLE
Crawler stuck indefinitely

### ISSUE THREAD

**Issue by fredrikekelund** [cgiffard/node-simplecrawler#144] opened 2015-06-02 12:38 UTC
I'm having an issue where the crawler gets stuck for an indefinite amount of time (until, in my code, it is manually aborted after a timeout of 5 minutes). Since every individual request has a configured timeout of 1 minute, it shouldn't be possible for the crawler to reach the 5 minute mark without any activity.

I suspect this is related to #136 and occurs after the crawler has encountered a number of timeouts (although I haven't seen any pattern where this problem always arises after X number of timeouts).

I tried temporarily downgrading to see if the suggestion that this problem was introduced somewhere around 40a71c1c5abffc2729316f4a90a0cb70b056612f might hold some truth, and it does seem like 0.3.11 doesn't have the same problem.

**Comment by cgiffard** [comment] 2015-06-02 12:52
Thanks for filing an issue! I have a bad feeling that this one is going to be hard to reproduce. :-/

Have you run into this when crawling any publicly accessible sites?

**Comment by fredrikekelund** [comment] 2015-06-02 12:58
Yeah I think you might be right about that... One of the sites that I've encountered the issue while crawling is http://www.egrillen.se/. Probably the most relevant crawler configuration is here (more or less directly copy-pasted):

```js
var crawler = new Crawler(this.options.domain, this.options.basePath);
crawler.interval = 50;
crawler.maxConcurrency = 5;

crawler.downloadUnsupported = false;
crawler.timeout = 60 * 1000;

/* Certain resources have a Content-Type set to None, in which case it's not
 * unlikely that the response is still some type of raw text and we want to
 * parse the document */
crawler.supportedMimeTypes.push(/none/i);
```

I'll try and set up a barebones crawler run of that site and report back on the results!

**Comment by fredrikekelund** [comment] 2015-06-02 13:50
Okay, so I slimmed down my code to start to isolate the problem. The crawler ran for about 10 minutes, with ~400 hits (about 50 of those were timeouts and 29 were 404's). Here's the [entire log](http://pastebin.com/g6mA6SDh), and here's the code I used (running this with simplecrawler v0.5.2). @cgiffard, see if you can reproduce the problem with this:

```js
var Crawler = require("simplecrawler");

var crawler = new Crawler("www.egrillen.se");
crawler.interval = 50;
crawler.maxConcurrency = 5;

crawler.downloadUnsupported = false;
crawler.timeout = 60 * 1000;

/* Certain resources have a Content-Type set to None, in which case it's not
 * unlikely that the response is still some type of raw text and we want to
 * parse the document */
crawler.supportedMimeTypes.push(/none/i);

crawler.addFetchCondition(function (parsedUrl) {
	return !/\.(jpeg|jpg|png|gif|ico|css|js|pdf)$/i.test(parsedUrl.uriPath);
});

var log = function () {
	lastRunMsAgo = 0;

	var time = /(\d+:\d+:\d+)/.exec(new Date().toString())[1];
	Array.prototype.unshift.call(arguments, time);
	console.log.apply(console, arguments);
};

var freezeAfter = 5 * 60 * 1000,
	lastRunMsAgo = 0;

var stopScraperInterval = setInterval(function () {
	lastRunMsAgo += 100;

	if (lastRunMsAgo >= freezeAfter) {
		clearInterval(stopScraperInterval);
		log("Stopping crawler because of timeout after", freezeAfter / 1000, "seconds");
		process.exit();
	}
}, 100);

crawler
	.on("fetchcomplete", function (queueItem, responseBuffer, response) {
		log("Done:", queueItem.url);
	})
	.on("fetch404", function (queueItem, responseBuffer) {
		log("404:", queueItem.url);
	})
	.on("fetcherror", function (queueItem, responseBuffer) {
		log("Error:", queueItem.url);
	})
	.on("fetchtimeout", function (queueItem, timeoutVal) {
		log("Timeout:", queueItem.url);
	})
	.on("complete", function () {
		clearInterval(stopScraperInterval);
		console.timeEnd("Crawl");
		log("Finished scraping!");
	});

console.time("Crawl");
crawler.start();
```

**Comment by fredrikekelund** [comment] 2015-06-23 14:33
@cgiffard have you had a chance to try and reproduce the problem using my test case?

**Comment by tschoartschi** [comment] 2015-07-21 06:15
@fredrikekelund @cgiffard I'm experiencing the same issue. Is there any solution?

**Comment by cgiffard** [comment] 2015-09-10 10:38
I still haven't managed to reproduce the problem, but I merged a PR from a user with a purported fix... could you check again?

**Comment by tschoartschi** [comment] 2015-09-10 11:21
I had to crawl a website to archive it. Because it was very urgent I ended up adding random query params to every link on the website. Then the problem was gone. I can not try it again, because the website is already offline. Sorry...

**Comment by fredrikekelund** [comment] 2015-09-10 11:26
I'm experiencing the same issue with 0.5.3

**Comment by fredrikekelund** [comment] 2015-09-15 14:14
I'm taking a look at this!

**Comment by cgiffard** [comment] 2015-09-15 22:01
I suspect it's worth first creating a test suite with a more comprehensive crawl, to reproduce this issue.

**Comment by fantapop** [comment] 2015-09-16 00:49
I ran into this as well. If I recall correctly I believe it's related to connection keepalives. I'm away from my code at the moment but I believe I had to set a node environment variable to get past this. Maybe @boushley Can take a look at my script.

**Closed** 2015-09-16 12:08 UTC
