### ISSUE TITLE
on('fetchcomplete') responseBody.toString('utf8') error "Disallowed Key Characters"

### ISSUE THREAD

**Issue by liesislukas** [cgiffard/node-simplecrawler#311] opened 2016-07-25 12:08 UTC
- [x] I have read the contributing guidelines.

### What happened (Observed behaviour)
got error "Disallowed Key Characters"

### What should happen (Expected behaviour)

get html of http://peterbiltradiators.ca/catalog

### Steps to reproduce the problem (include code examples)

```js
  crawler.on('fetchcomplete', (queueItem, responseBody, responseObject) => {
    console.log(`Completed fetching resource: ${queueItem.url}`);
    console.log(`responseBody.toString('utf8'): ${responseBody.toString('utf8')}`);
...
```
result:

```
Completed fetching resource: http://peterbiltradiators.ca/catalog
responseBody.toString('utf8'): Disallowed Key Characters.
```

You don't even have to call toString('utf8') it still returns `Disallowed Key Characters`

**Comment by fredrikekelund** [comment] 2016-07-31 10:46
I tried reproducing your problem with the following code, but didn't manage to get the problem to appear. Could you post a more complete sample of your code? That way we'll be able to tell if something seems off

This was my test code:

```js
var Crawler = require("simplecrawler");

var crawler = new Crawler("peterbiltradiators.ca", "/catalog");

crawler.on("fetchcomplete", (queueItem, responseBody, responseObject) => {
    console.log(`Completed fetching resource: ${queueItem.url}`);
    console.log(`responseBody.toString('utf8'): ${responseBody.toString('utf8')}`);
});

crawler.on("complete", () => {
    console.log("Crawl completed!");
});

crawler.start();
```

**Comment by cgiffard** [comment] 2016-08-02 02:38
Thanks for filing an issue!

This is likely to be an issue with the encoding of the page in question — it is likely that it was corrupt or unable to be parsed. Unfortunately unless we can reproduce the issue locally (and it is demonstrated that `simplecrawler` is responsible for corrupting the data) it is not likely to be something we can fix. Instead, try coercing the page to ASCII or an encoding which will disregard character sequences. The `Buffer.prototype.toString` method is provided by Node.js itself, and it is advisable that if you continue to have problems it might be better to address this question to the Node.js repo.

I'm closing this issue as 'unable to reproduce', but if you vehemently disagree with anything I've written here, don't hesitate to let me know.

**Closed by cgiffard** 2016-08-02 02:38 UTC
