### ISSUE TITLE
addFetchCondition receiving broken path in 0.5.3

### ISSUE THREAD

**Issue by tedbjorling** [cgiffard/node-simplecrawler#172] opened 2015-09-20 20:06 UTC
In version 0.5.3, the path attribute of the parameter object of the addFetchCondition function is erroneus, as the path string now seems to be prefixed with "%22", e.g. path:"%22/foo/bar" instead of "/foo/bar". Downgrading to 0.5.2 yields the correct behaviour.

**Comment by fredrikekelund** [comment] 2015-09-22 11:41
I can't reproduce this right off the bat, can you give me a test case to look into?

I tested using the follow code, and that didn't log any URL's
```js
"use strict";

var Crawler = require("simplecrawler");
var crawler = new Crawler("www.theguardian.com", "/uk");

crawler.addFetchCondition(function (parsedUrl) {
	if (/^%22/.test(parsedUrl.path))
		console.log(parsedUrl.path);

	return true;
});

crawler.start();

```

**Comment by fredrikekelund** [comment] 2015-10-16 11:49
@tedbjorling bump. I still haven't been able to reproduce this, wondering whether you're still having trouble with this or not

**Comment by tedbjorling** [comment] 2015-11-14 21:56
@fredrikekelund sorry for not replying sooner, but the issue was with the `discoverRegex` I was using. The following worked fine in the 0.5.2 version, while produced the aforementioned result in 0.5.4:
```
		/(\shref\s?=\s?)([^\"\'\s>\)]+)/ig,
		/(\shref\s?=\s?)['"]([^"']+)/ig,
```

**Comment by fredrikekelund** [comment] 2015-11-15 11:12
Hmm a bit strange that the result of the regex would change between the versions though. And I don't see how either of them would capture any quotes. Have you looked at the diffs between the two versions to see what might've triggered the problem?

**Comment by sethbridges** [comment] 2015-11-24 18:52
In the 0.5.4 version, I'm getting fetch404 errors because the crawler is somehow finding paths that look like /3%22 that clearly don't exist on my page.

Here's a test for you that crawls our marketing site with a depth of one and returns a single fetch404 error with this style path.

I spent the 15 mins to find out where it is getting this 3" from, and it is a regex bug:

This link is on our page, and it is matching the goop in the querystring src=3"

<a href="https://plus.google.com/103804658836845491492?prsrc=3" target="_blank" class="footer-nav-list-link">Google+</a>

```javascript
var Crawler = require("simplecrawler");

var myCrawler = new Crawler("www.rivaliq.com");

myCrawler.maxDepth = 1;
myCrawler.interval = 250; 
myCrawler.maxConcurrency = 1;
myCrawler.parseScriptTags = false;
myCrawler.initialProtocol = "https";


myCrawler.on("fetch404", function(queueItem, response) {
  console.log('fetch404', queueItem.url, queueItem.referrer);

});

myCrawler.on("fetcherror", function(queueItem, response) {
  console.log('fetcherror ' + queueItem.url);
    // Do something with the data in responseBuffer
});

myCrawler.start();
```

**Comment by sethbridges** [comment] 2015-11-30 23:18
@fredrikekelund 

bump.

The regex that is matching this expression doesn't require a space before the space attribute. This is leading to the match of src=3" when embedded into another url (e.g., as a querystring param).

From crawler.js:

```
crawler.discoverRegex = [
        /\s?(?:href|src)\s?=\s?(["']).*?\1/ig,
        /\s?(?:href|src)\s?=\s?[^"'][^\s>]+/ig,
        /\s?url\((["']).*?\1\)/ig,
        /\s?url\([^"'].*?\)/ig,
```

**Comment by sethlesky** [comment] 2015-12-11 04:19
@sethbridges @fredrikekelund I believe I'm seeing the same, or related behavior. I crawled a site that has javascript within a script tag.

   		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		  ga('create', 'UA-67238765-1', 'auto');
		  ga('send', 'pageview');

		</script>

When this site is crawled it results in loop preventing the crawl to complete. URLs grow each request appending parts of the javascript.

```
http://www.psychedelicchat.com/
http://www.psychedelicchat.com/%28.%2A%29/%29;
http://www.psychedelicchat.com/matches%5B1%5D;
http://www.psychedelicchat.com/%28.%2A%29/g;m.parentNode.insertBefore%28a,m%29
http://www.psychedelicchat.com/%28.%2A%29/matches%5B1%5D;
http://www.psychedelicchat.com/g;m.parentNode.insertBefore%28a,m%29
http://www.psychedelicchat.com/%28.%2A%29/%28.%2A%29/%29;
http://www.psychedelicchat.com/%28.%2A%29/%28.%2A%29/matches%5B1%5D;
http://www.psychedelicchat.com/%28.%2A%29/%28.%2A%29/%28.%2A%29/%29;
http://www.psychedelicchat.com/%28.%2A%29/%28.%2A%29/%28.%2A%29/matches%5B1%5D;
http://www.psychedelicchat.com/%28.%2A%29/%28.%2A%29/g;m.parentNode.insertBefore%28a,m%29
```

Or URL decoded

```
http://www.psychedelicchat.com/
http://www.psychedelicchat.com/(.*)/);
http://www.psychedelicchat.com/matches[1];
http://www.psychedelicchat.com/(.*)/g;m.parentNode.insertBefore(a,m)
http://www.psychedelicchat.com/(.*)/matches[1];
http://www.psychedelicchat.com/g;m.parentNode.insertBefore(a,m)
http://www.psychedelicchat.com/(.*)/(.*)/);
http://www.psychedelicchat.com/(.*)/(.*)/matches[1];
http://www.psychedelicchat.com/(.*)/(.*)/(.*)/);
http://www.psychedelicchat.com/(.*)/(.*)/(.*)/matches[1];
http://www.psychedelicchat.com/(.*)/(.*)/g;m.parentNode.insertBefore(a,m)
http://www.psychedelicchat.com/(.*)/(.*)/(.*)/(.*)/);
http://www.psychedelicchat.com/(.*)/(.*)/(.*)/g;m.parentNode.insertBefore(a,m)
http://www.psychedelicchat.com/(.*)/(.*)/(.*)/(.*)/(.*)/);
http://www.psychedelicchat.com/(.*)/(.*)/(.*)/(.*)/matches[1];
http://www.psychedelicchat.com/(.*)/(.*)/(.*)/(.*)/(.*)/g;m.parentNode.insertBefore(a,m)
http://www.psychedelicchat.com/(.*)/(.*)/(.*)/(.*)/g;m.parentNode.insertBefore(a,m)
http://www.psychedelicchat.com/(.*)/(.*)/(.*)/(.*)/(.*)/(.*)/);
http://www.psychedelicchat.com/(.*)/(.*)/(.*)/(.*)/(.*)/matches[1];
```

**Comment by cgiffard** [comment] 2015-12-15 04:03
Simplecrawler optimistically looks for URLs, even if those URLs might be messy or invalid — the rationale being it's better not to miss something and get a bunch of 404s, than to keep things clean and maybe miss a resource.

You can change the discovery function or tune the behaviour of the inbuilt discoverer if this is a problem.

The escaping, though, is a separate issue.

**Comment by fredrikekelund** [comment] 2015-12-21 07:53
@sethlesky did you disable the `parseScriptTags` option? That should hopefully help with simplecrawler not picking up JavaScript code as URL's

**Comment by fredrikekelund** [comment] 2015-12-21 08:25
@sethbridges I've pushed a commit that fixes the issue with 'href' or 'src' strings inside URL's. Give https://github.com/cgiffard/node-simplecrawler/commit/5442be48e96af15f01760026d096be0677c0a70c a try and let me know if you have any problems! I'll close this in the meantime

**Closed by fredrikekelund** 2015-12-21 08:25 UTC
Labels: Bug

**Comment by sethbridges** [comment] 2015-12-21 21:19
@fredrikekelund thanks, that did the trick.
