### ISSUE TITLE
halting problem, the `complete` event never stops being fired

### ISSUE THREAD

**Issue by weisjohn** [cgiffard/node-simplecrawler#276] opened 2016-04-25 22:10 UTC
The callback is continually fired 

on
```
$ node -v
v5.10.1
```

index.js: 

```javascript

var Crawler = require("simplecrawler");

var url = 'http://johnweis.com/';

var crawler = Crawler.crawl(url);

var isHTML = /text\/html/;

crawler.on("fetchcomplete", function(queueItem) {
  if (isHTML.test(queueItem.stateData.contentType)) {
    console.log('found html', queueItem.url);
  }
});

crawler.on('complete', function() {
  console.log('complete');
});

crawler.start();

```

output:

```
$ ndb
found html http://johnweis.com/
found html http://johnweis.com/talks
found html http://johnweis.com/projects
found html http://johnweis.com/static/tessel/
found html http://johnweis.com/static/intro_to_phantomjs/
found html http://johnweis.com/static/learn_node/
found html http://johnweis.com/static/RxD/index.html
found html http://johnweis.com/static/css_mq/index.html
complete
complete
complete
complete
complete
complete
complete
complete
complete
[...]
```

**Comment by weisjohn** [comment] 2016-04-25 22:15
probably related to #206 ?

**Comment by cgiffard** [comment] 2016-04-26 04:19
Hrm, this is an interesting one. Thanks for filing an issue — I'll try to reproduce this tonight. :)

**Comment by fredrikekelund** [comment] 2016-04-26 10:44
If you're running 0.6.2, the problem is the same as in #206, where the crawler is actually started twice, which generates two main loops, of which only one is cleared when the crawler finishes. Solution would be to remove the `crawler.start` call on line 19 (or use the latest master, which protects against the crawling starting again when it's already running).

A new release is coming some time in the next two weeks that protects against this scenario as well!

**Comment by fredrikekelund** [comment] 2016-05-06 09:18
Closing this until further notice. Just let us know if the problem persists, @weisjohn!

**Closed by fredrikekelund** 2016-05-06 09:18 UTC
Labels: Bug
