### ISSUE TITLE
events thrown for notfound and then for timeout

### ISSUE THREAD

**Issue by fantapop** [cgiffard/node-simplecrawler#136] opened 2015-05-13 23:59 UTC
I'm seeing some strange behaviour when using this. I'm crawling my site and for some links a 404 is thrown and then a timeout is thrown.  The timeouts queue items still have the 404 response code in them but the status is updated to timeout:

```
{ url: 'https://localhost:4443/current/web-ui-users-guide/&apos;Resources/PageLayouts/Default.flpgl&apos;',
  protocol: 'https',
  host: 'localhost',
  port: '4443',
  path: '/current/web-ui-users-guide/&apos;Resources/PageLayouts/Default.flpgl&apos;',
  depth: 4,
  fetched: true,
  status: 'timeout',
  stateData:
   { requestLatency: 6,
     requestTime: 6,
     contentLength: 8961,
     contentType: 'text/html; charset=UTF-8',
     code: 404,
     headers:
      { 'x-powered-by': 'Express',
        'accept-ranges': 'bytes',
        date: 'Wed, 13 May 2015 23:45:22 GMT',
        'cache-control': 'public, max-age=0',
        'last-modified': 'Wed, 10 Sep 2014 22:45:00 GMT',
        etag: 'W/"2301-2511629950"',
        'content-type': 'text/html; charset=UTF-8',
        'content-length': '8961',
        connection: 'keep-alive' } },
  referrer: 'https://localhost:4443/current/web-ui-users-guide/' }
```

I'm looking at this somewhat recent commit: 40a71c1c5abffc2729316f4a90a0cb70b056612f

It looks like the timeout code used to check to see if there was already a response and abort if so but now its emitting the timeout no matter what.

**Comment by cgiffard** [comment] 2015-09-14 23:24
I think this is a duplicate of #144 — if I'm wrong, please don't hesitate to reopen the issue.

**Comment by fantapop** [comment] 2015-09-16 00:44
When I found this issue, node-simplecrawler was unusable for me so I had to roll back to a previous version.  At the time I also experienced issue 144. For this reason I don't think they are related. I'll comment on 144 as well because I think I found a work around.  I believe the bug for this issue is in the commit I referenced.

**Comment by fredrikekelund** [comment] 2015-09-16 14:13
Looking at the solution to that problem, I'm not sure #144 was related to this either. @fantapop could you check if you're experiencing the same issues with the latest `master`?

**Comment by fantapop** [comment] 2015-09-16 18:55
I'm currently on vacation so it will be a little while. A couple of weeks.
I'll try to remember to check back here when I'm home.

**Comment by fredrikekelund** [comment] 2015-09-18 07:47
I can confirm that this is still an issue, even with the latest changes in master. Looking into it!

**Closed** 2015-10-02 01:40 UTC
