### ISSUE TITLE
Crawler seems to error out as 'ECONNRESET'?

### ISSUE THREAD

**Issue by iDVB** [cgiffard/node-simplecrawler#151] opened 2015-07-23 13:25 UTC
```javascript

var Crawler = require("simplecrawler");

var url = "www.salix.com"
var myCrawler = new Crawler(url);

myCrawler.interval = 1000;
myCrawler.maxConcurrency = 5;
myCrawler.maxDepth = 2;

myCrawler.addFetchCondition(function(parsedURL) {
    if (parsedURL.path.match(/\.(css|jpg|pdf|docx|js|png|ico)/i)) {
        console.log("KILLED!",parsedURL.path);
        return false;
    }

    return true;
});


myCrawler.on('fetchstart', function(queueItem, responseBuffer, response){
	 console.log("about to crawl: ", queueItem.url, responseBuffer.length);
});

myCrawler.on('fetchclienterror', function(queueItem, errorData){
	 console.log("fetchclienterror: ", queueItem.url, errorData);
});

myCrawler.on('fetchtimeout', function(queueItem, crawlerTimeoutValue){
	 console.log("fetchtimeout: ", queueItem.url, crawlerTimeoutValue);
});



myCrawler.on('fetchcomplete', function(queueItem, responseBuffer, response){
	 console.log("I just received %s (%d bytes)", queueItem.url, responseBuffer.length);
   console.log("It was a resource of type %s", response.headers['content-type']);
});

myCrawler.on('complete', function(){
	 console.log('FIN!');
});

myCrawler.start();
```

I end up getting what looks like a ton of `fetchstart`s but ends up exponentially slowing down with each until it seems to almost just halt.

![err](http://goo.gl/xHgaRW)

**Comment by iDVB** [comment] 2015-07-23 13:38
Seems to be slowing on this page.....   
http://www.salix.com/about-us/governance-compliance/vermont-prescribers-information

which has a ton of PDFs on it.... still not sure what the issue is though as I'm not getting any errors or output.

**Comment by iDVB** [comment] 2015-07-23 14:54
What I don't understand is, if I'm consoling out all events (since added more then above) why would the crawler stall without ANY logging? It just hangs there for a VERY long time.

**Comment by ahansson89** [comment] 2015-08-14 03:45
I have the same issue.

**Comment by cgiffard** [comment] 2015-09-14 23:21
I believe this issue is a duplicate of #144. I'm going to add a much bigger test suite to verify that all the crawl behaviours are working as intended — there was a bug introduced some time back where the crawler will just hang in the event of an error, but I haven't found it yet.

**Closed by cgiffard** 2015-09-14 23:21 UTC
