### ISSUE TITLE
Ways to retry failed crawls?

### ISSUE THREAD

**Issue by liang3404814** [cgiffard/node-simplecrawler#286] opened 2016-06-10 21:31 UTC
I'm trying to get the crawler to throw failed urls back into the queue for retries by doing the following:

```
crawler.on("fetcherror", function(queueItem, response) {
    console.log("ERROR for %s", decodeURI(queueItem.url));
    console.log("ERROR is %s", response.statusCode);
    crawler.queueURL(queueItem.url);
});
```

and then I tested out with one url, invalid, failed, but the crawler completes anyway without retrying.

Am I doing this right? I have searched in the issues and don't see anything mentioning retries.

**Comment by cgiffard** [comment] 2016-06-11 06:48
You're right in that there's no (currently good) way to get stuff back into the queue which has failed. If you use queueURL, the URL will not be added to the queue as it's a duplicate of the one which is already in there.

We should probably add an API explicitly for retrying. There's a proposed API for removing from the queue/requeue in #256. In the meantime you could try manually deleting the queued item.

Apologies for the hassle! I hope to have a better answer for you soon. :)

**Comment by fredrikekelund** [comment] 2016-09-30 11:23
With the 1.0.0 release, we updated the `Crawler#queueURL` method to accept a third parameter: `force`. If you set that to true, any checks for whether or not the item already exists in the queue will be bypassed, and the URL will still be added. Let us know if you have any trouble with it, I'll close this issue

**Closed by fredrikekelund** 2016-09-30 11:23 UTC
Labels: New Feature, Underway
