### ISSUE TITLE
Crawling a website which returns header with invalid charecters?

### ISSUE THREAD

**Issue by ibex-of-entropy** [cgiffard/node-simplecrawler#321] opened 2016-08-12 21:35 UTC
Crawlers says

```
/home/cat/Dropbox/firm-email-crawler/node_modules/simplecrawler/lib/crawler.js:1124
            throw e;
            ^

TypeError: The header content contains invalid characters
    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:348:11)
    at new ClientRequest (_http_client.js:85:14)
    at Object.exports.request (http.js:31:10)
    at /home/cat/Dropbox/firm-email-crawler/node_modules/simplecrawler/lib/crawler.js:1119:40
    at FetchQueue.update (/home/cat/Dropbox/firm-email-crawler/node_modules/simplecrawler/lib/queue.js:226:9)
    at Crawler.fetchQueueItem (/home/cat/Dropbox/firm-email-crawler/node_modules/simplecrawler/lib/crawler.js:1096:19)
    at /home/cat/Dropbox/firm-email-crawler/node_modules/simplecrawler/lib/crawler.js:1698:25
    at FetchQueue.oldestUnfetchedItem (/home/cat/Dropbox/firm-email-crawler/node_modules/simplecrawler/lib/queue.js:247:13)
    at Crawler.crawl (/home/cat/Dropbox/firm-email-crawler/node_modules/simplecrawler/lib/crawler.js:1650:19)
    at Timeout.wrapper [as _onTimeout] (timers.js:417:11)
```

on http://bizconsult-vietnam.com/

**Comment by cgiffard** [comment] 2016-08-22 04:23
Can you provide a code example demonstrating the problem?

**Comment by ibexofentropy** [comment] 2016-08-29 14:15
```



var cheerio = require("cheerio")
var SimpleCrawler = require("simplecrawler");

var resourceTextSortRatings = [
	/info/i,
	/about/i,
	/contact/i,
];

var crawl = function (url, completeCb) {

	var crawler = new SimpleCrawler(url);
	crawler.allowInitialDomainChange = true;
	crawler.filterByDomain = false;
	crawler.maxDepth = Infinity;
	crawler.interval = 1500;
	crawler.timeout = 15000;
	crawler.maxConcurrency = 1;
	crawler.respectRobotsTxt = false;
	crawler.maxResourceSize = 4194304; // 4MB

	var timeoutID = null;
	var isQuickTimeout = false;
	var timeoutCb = function () {
		timeoutID = null;
		crawler.stop();
		complete();
	};
	
	timeoutID = setTimeout(timeoutCb, 40 * 1000);

	var emails = new Set();

	crawler.discoverResources = function(buffer, queueItem) {
		var $ = cheerio.load(buffer.toString("utf8"));

		var html = $("body").html();
		if (html) {
			var matches = html.match(/\b[\w\.-]+@[\w\.-]+\.\w+\b/g);

			if (matches) {
				matches = matches.map(function (match) {
					return match.replace(/@.*$/, function (domain) {
						return domain.toLowerCase();
					});
				});

				matches.forEach(function (match) {
					emails.add(match);
				});

			}
		}

		var resources = [];

		var meta = $("head meta[http-equiv=refresh]");
		if (meta.length) {
			meta = meta.last();
			var content = meta.attr("content");
			if (content) {
				var matches = content.match(/;url=(.*)$/);
				if (matches) {
					resources.push(matches[1]);
				}
			}
		}

		resources.push(...Array.from(
			$("a[href]")
		).map(function (anchor) {
			return cheerio(anchor);
		}).filter(function (anchor) {
			return !/\.pdf$/i.test(anchor.attr("href"));
		}).sort(function (a, b) {
			a = a.text();
			b = b.text();
			return 0 +
				resourceTextSortRatings.findIndex(function (test) {
					return test.test(b);
				}) - 
				resourceTextSortRatings.findIndex(function (test) {
					return test.test(a);
				})
			;
		}).map(function (anchor) {
			return anchor.attr("href");
		}));

		return resources;
	};

	crawler.addFetchCondition(function(parsedURL, queueItem) {
	    
	    return parsedURL.depth <= crawler.maxDepth;
	});

	var isComplete = false;
	crawler.on("complete", function() {
		if (timeoutID) {
			clearTimeout(timeoutID);
			complete();
		}
	});

	var complete = function () {
		if (!isComplete) {
			isComplete = true;
			console.log("complete");
		} else {
			console.log("complete twice???");
		}
	};

	var originalEmit = crawler.emit;
	crawler.emit = function(evtName, queueItem) {
		var data;
		crawler.queue.countItems({ fetched: true }, function(error, completeCount) {
	        if (error) {
	            throw error;
	        }

	        crawler.queue.getLength(function(err, length) {
	            if (err) {
	                throw err;
	            }

	            data = 
	                completeCount + " " +
	                length + " " +
	                crawler._openRequests.length + " " +
	                crawler._openListeners
	            ;
	            data = " ".repeat(16 - data.length) + data;
	        });
	    });

		console.log(data, evtName, queueItem ? queueItem.url ? queueItem.url : queueItem : null);
		originalEmit.apply(crawler, arguments);
	};

	crawler.start();
};



crawl("http://bizconsult-vietnam.com/");
```

**Comment by ahansson89** [comment] 2016-12-07 18:23
Any news on this issue?

**Comment by fredrikekelund** [comment] 2017-04-07 08:20
Coming back to this now, I'm having difficulties reproducing the problem. With the exact test case you provided, @ibex-of-entropy, the crawler runs for just a few seconds and then completes. If I remove the custom discoverResources method (which seems to not be working fully in your sample) and re-enable `Crawler#filterByDomain`, it runs through about 80 URL's and then completes.

From the stack trace you provided, it looks like the issue is encountered on outgoing requests, not incoming responses. But it would indeed be likely that it's because of an invalid header that's been returned from the website and stored in simplecrawler.

Have you seen more of this issue, @ibex-of-entropy? Or is this something you also have encountered @ahansson89?

**Comment by fredrikekelund** [comment] 2017-07-25 15:53
I'll close this issue for now because it hasn't been active in a while. If you encounter this again, don't hesitate to drop a comment and I will re-open it. Ping @ahansson89 and @ibex-of-entropy

**Closed by fredrikekelund** 2017-07-25 15:53 UTC
Labels: Bug
