### ISSUE TITLE
Cookies are not added to the jar

### ISSUE THREAD

**Issue by ToastHelmi** [cgiffard/node-simplecrawler#96] opened 2014-11-18 11:00 UTC
Headers 1 Request
```
{"User-Agent":"Node/simplecrawler 0.3.10 (http://github.com/cgiffard/node-simplecrawler.git)","Host":"www.golem.de","cookie":[]}
```

Headers 1 response
```
{"server":"nginx","date":"Tue, 18 Nov 2014 10:55:33 GMT","content-type":"text/ht
ml; charset=UTF-8","transfer-encoding":"chunked","connection":"keep-alive","keep
-alive":"timeout=3","vary":"Accept-Encoding","set-cookie":["golem_viewauto=deskt
op%3Ageneric; expires=Tue, 18-Nov-2014 22:55:33 GMT; path=/; domain=.golem.de"],
"x-upstream":"www1.golem.de"}
```

Headers 2. Request
```
{"User-Agent":"Node/simplecrawler 0.3.10 (http://github.com/cgiffard/node-simple
crawler.git)","Host":"www.golem.de","Referer":"http://www.golem.de/","cookie":[]
}
```

**Comment by fredrikekelund** [comment] 2016-03-16 12:17
I'm looking to see whether this is still reproducable later this week. Just wanted to check if you know that something cookie related has changed since this issue was reported, @cgiffard?

**Comment by cgiffard** [comment] 2016-03-22 12:10
I don't recall having changed anything — cookie logic has been fairly static.

**Comment by fredrikekelund** [comment] 2016-03-22 14:34
I had an initial look into this and couldn't reproduce it. Would still like to confirm (because I ran into some other issue), but most likely this bug is no longer present

**Comment by cgiffard** [comment] 2016-03-23 12:10
Do you think we should close this for now, then?

**Comment by fredrikekelund** [comment] 2016-03-24 07:39
I'll spend some time on this tonight just to confirm!

**Comment by fredrikekelund** [comment] 2016-03-24 21:11
Closing this since I confirmed that simplecrawler indeed deals with cookies correctly.

**Closed by fredrikekelund** 2016-03-24 21:11 UTC
Labels: Bug
