### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by thomasmodeneis** [cgiffard/node-simplecrawler#334] opened 2016-10-29 08:01 UTC
## What happened?
```
/opt/tst/node_modules/css-select/lib/general.js:21
			return getName(elem) === name && next(elem);
			       ^

RangeError: Maximum call stack size exceeded
    at tag (/opt/tst/node_modules/css-select/lib/general.js:21:11)
    at findAll (/opt/tst/node_modules/domutils/lib/querying.js:87:6)
    at findAll (/opt/tst/node_modules/domutils/lib/querying.js:90:27)
    at findAll (/opt/tst/node_modules/domutils/lib/querying.js:90:27)
    at findAll (/opt/tst/node_modules/domutils/lib/querying.js:90:27)
    at findAll (/opt/tst/node_modules/domutils/lib/querying.js:90:27)
    at findAll (/opt/tst/node_modules/domutils/lib/querying.js:90:27)
    at findAll (/opt/tst/node_modules/domutils/lib/querying.js:90:27)
    at findAll (/opt/g10/node_modules/domutils/lib/querying.js:90:27)
    at findAll (/opt/tst/node_modules/domutils/lib/querying.js:90:27)
    at findAll (/opt/tst/node_modules/domutils/lib/querying.js:90:27)
    at findAll (/opt/g10/node_modules/domutils/lib/querying.js:90:27)
    at findAll (/opt/tst/node_modules/domutils/lib/querying.js:90:27)
    at findAll (/opt/tst/node_modules/domutils/lib/querying.js:90:27)
    at findAll (/opt/tst/node_modules/domutils/lib/querying.js:90:27)
    at findAll (/opt/tst/node_modules/domutils/lib/querying.js:90:27)
```
## Steps to reproduce the problem
Just left it running overnight and got this :|

config:
```
crawler.maxDepth = 3; // Etc.
crawler.interval = 250;
crawler.maxConcurrency = 5;
version: "simplecrawler": "1.0.3",

```

Any ideas or something ?

**Comment by cgiffard** [comment] 2016-10-29 10:54
Hey — thanks for filing an issue!

That doesn't look like a simplecrawler bug, unfortunately — as far as I was able to ascertain from a fresh install, neither simplecrawler or any of its dependencies use domutils or css-select. Perhaps check with the author of css-select and domutils over in their repo: https://github.com/FB55/domutils

As an aside, there's very little information to go on, there. I would encourage you to provide more information with your next bug report, like the sites you're crawling (if possible) as well as a limited working test case we can run. I can plug the configuration you provided into simplecrawler here, and run it against a site, but there's no guarantee I'll ever see the issue you're experiencing — especially if the issue is occurring in another dependency.

That said, best of luck resolving your issue!

**Closed by cgiffard** 2016-10-29 10:54 UTC

**Comment by thomasmodeneis** [comment] 2016-10-29 11:15
haha ok man, you can say whatever you want, is your repo.
But there is a bug in there and you closed the issue, so whatever.
Best luck with it.

**Comment by cgiffard** [comment] 2016-10-29 11:35
Hey — not trying to be combative here. I want to help you fix your problem as much as possible and help improve the quality of the crawler code if I can. :)

That said, I don't have much to work with, and the stack trace you provided points to a tight loop in code which *flat out isn't part of node-simplecrawler or any of its dependencies*, so unless I have a bit more information to help me reproduce it, there's not much I can do, I'm sorry!

**Comment by thomasmodeneis** [comment] 2016-10-31 09:08
Ok mate, I see now that that flat code is not part of simplecrawler and I'm looking to identify where that come from.
But when you just close the ticket you are not really allowing a conversation, you are just closing it.
When someone spend the time to come here and file you a defect, it will be nice if you could give this person some time to adapt to your requests and not just close the door just like that.
Have a good week,
Cheers.

**Comment by cgiffard** [comment] 2016-10-31 09:44
No worries at all — I'm sorry you felt I was closing the door, as that was not the intention at all! More than happy to keep the discussion going, even on a closed ticket.

Have a good week too. :)
