### ISSUE TITLE
Crawler pauses for over 1 minute before resuming

### ISSUE THREAD

**Issue by grommett** [cgiffard/node-simplecrawler#108] opened 2015-02-22 19:39 UTC
After the crawler runs for a while it suddenly pauses and waits for over a minute to resume. In some cases I've seen it wait for almost 2 minutes. This occurs with the default ```crawler.maxConcurrency``` and up to ```crawler.maxConcurrency = 40```. 

Code:
```
var site = 'ni.com';
var crawler = new Crawler(site);

crawler
  .on('fetch404',function(queueItem, response) {
    console.error('Resource not found linked from ' + queueItem.referrer+ ' to', queueItem.url.magenta);
  })
  .on('fetchcomplete', function(queueItem, responseBuffer) {
    console.log('Fetched: ' + queueItem.url);
  });

crawler.start();
```
I've had a look at the source and I'm not sure why this is happening. Any ideas on how to prevent this?

**Comment by tedbjorling** [comment] 2015-02-24 20:41
I am seeing this behaviour as well, and have concluded that it is related to the timeout variable. Changing this from the default 5 minutes to, say, 10 seconds, softens the effect of this intermittent delay bug. The site I am trying this on is responsive, so it is definitely not a server issue.

**Comment by grommett** [comment] 2015-02-24 23:30
@tedbjorling Thanks. Changing the timeout variable does seem to help.

**Comment by cgiffard** [comment] 2015-02-25 12:26
The default is very permissive. If the server being crawled fails to respond or hangs onto the connection for long periods of time without delivering anything—and this happens frequently enough, the entire allotment of concurrent requests may be exhausted and the crawler will halt, until such time as one or more of the requests occupying the concurrent request allotment expires.

Perhaps 5 minutes could be shrunk to 3, or 1—but I'm not sure there's a bug here, unless the crawler is failing to recognise an error condition.

Have you observed any unhandled errors or has the crawler crashed at all during this time?

**Comment by tedbjorling** [comment] 2015-02-27 20:08
The issue is not so much unresponsive connections - the scenario in which this was brought to my attention involved a service which responded just fine. I believe there is a bug somewhere in the code that is provisioning the number of open requests, possibly related to the setTimeout functionality of the the http/https request. From what I could see, this function seemed to trigger a timeout even though a valid response have indeed been provided. I do not know if this is intentional or not, not being knowledgable in the standard http/https node.js libraries.

Anyhow, please try the following snippet:

var Crawler = require("simplecrawler");
Crawler.crawl("http://lindex.com/")
    .on("fetchcomplete",function(queueItem){
        console.log("Completed fetching resource:",queueItem.url);
    });

You will hopefully as well notice that it hits a set of URL:s (around 10), and then makes a pause for a couple of minutes (i.e. the value of the timeout variable) before continuing, even though the URL:s being hit responds timely and perfectly fine, at least as far as I can see.

**Comment by talss89** [comment] 2015-02-28 10:25
@tedbjorling - We're seeing the same behaviour with your snippet on Node 0.10.32.

We're also experiencing the issue with our implementation. As the problem seems to occur with certain sites, I'm wondering if it's to do with a bad HTTP response from the server. Possibly content-length...

Crawling http://asos.com/ also causes this behaviour.

**Comment by cgiffard** [comment] 2015-04-20 13:03
Hi All — please check the latest version. I believe this issue may have been corrected.

**Comment by cgiffard** [comment] 2015-04-21 22:39
Hi All — I'm closing this issue for now. If it is still happening, please just reopen. :)

**Closed by cgiffard** 2015-04-21 22:39 UTC
Labels: Bug, Triaged and Waiting for response

**Comment by grommett** [comment] 2015-04-21 22:41
Thanks @cgiffard! I'll give it a test in our next build and report back if we see the issue again.
